plugins:
  # 国际 DNS DoH 解析服务器
  - tag: "REMOTE_DOH"
    type: "forward"
    args:
      concurrent: 2
      upstreams:
        - tag: google_doh
          addr: "https://8.8.8.8/dns-query"
          socks5: "127.0.0.1:7893" # 使用socks5代理DOH查询
          idle_timeout: 30
          enable_pipeline: false
          enable_http3: false
          insecure_skip_verify: false
        - tag: cloudflare_doh
          addr: "https://1.1.1.1/dns-query"
          socks5: "127.0.0.1:7893" # 使用socks5代理DOH查询
          idle_timeout: 30
          enable_pipeline: false
          enable_http3: false
          insecure_skip_verify: false
          
  # 备用的可信 DNS DoH 解析服务器
  - tag: "BACKUP_DOH"
    type: "forward"
    args:
      concurrent: 1
      upstreams:
        - tag: apadpro_doh
          addr: "https://doh.apad.pro/dns-query"
          idle_timeout: 30
          enable_pipeline: false
          enable_http3: false
          insecure_skip_verify: false

  # 大陆 DNS DoH 解析服务器
  - tag: "CHINA_DOH"
    type: "forward"
    args:
      concurrent: 2
      upstreams:
        - tag: aliyun_doh
          addr: "https://223.5.5.5/dns-query"
          idle_timeout: 30
          enable_pipeline: false
          enable_http3: false
          insecure_skip_verify: false
        - tag: tencent_doh
          addr: "https://1.12.12.12/dns-query"
          idle_timeout: 30
          enable_pipeline: false
          enable_http3: false
          insecure_skip_verify: false