log:
  production: false
  level: info  # 日志级别 "debug" "info" "warn" "error"
  file: "./dns.log"

plugins:
  
  # 缓存
  - tag: "CACHE"
    type: "cache"
    args:
      size: 204800  # 内置内存缓存条数
      lazy_cache_ttl: 2592000  # lazy cache 生存时间秒。0=禁用， 86400（1天）604800（7天）2592000（30天）
      dump_file: "./cache.dump" # 缓存将在 mosdns 被关闭时保存,插件启动时也会自动从该文件载入缓存
      dump_interval: 60 #自动保存间隔秒
    
    # PTR
  - tag: "REVERSE_LOOKUP"
    type: "reverse_lookup"
    args:
      size: 65535 # 内置缓存大小。默认 65535。
      ttl: 7200 # 缓存时间。秒。默认 7200 (2h)。应答记录的 TTL 也会被自动修改，限制在该值以下。
      handle_ptr: true # 是否主动处理/响应 PTR 请求。如果 PTR 的 IP 命中缓存，则生成应答。
      # 用途举例: 使用网络监视类工具查看网络连接时，开启域名反查功能大概率会看到 IP 对应的
      # 真实域名(如果程序先请求域名再建立连接，而且域名经过了该插件处理。)
      
      
   # 配置ECS，为国内站点加速   
  - tag: "ECS_CHINA"
    type: "ecs_handler"
    args:
      forward: true        # 是否转发来自下游的 ecs
      preset: 114.241.101.101       # 发送预设 ecs.  北京联通ECS
      send: false           # 是否发送 ecs
      mask4: 16             # ipv4 掩码。默认 24
      mask6: 48             # ipv6 掩码。默认 48
      
  # 海外DNS DoH解析服务器
  - tag: "REMOTE_DOH"
    type: "forward"
    args:
      concurrent: 2
      upstreams:
        - tag: google_doh
          addr: "https://8.8.8.8/dns-query"
          socks5: "10.10.10.4:7893" # 使用socks5代理DOH查询
          idle_timeout: 30
          enable_pipeline: false
          enable_http3: false
          insecure_skip_verify: false
        - tag: cloudflare_doh
          addr: "https://1.1.1.1/dns-query"
          socks5: "10.10.10.4:7893" # 使用socks5代理DOH查询
          idle_timeout: 30
          enable_pipeline: false
          enable_http3: false
          insecure_skip_verify: false
          
    # 备用的可信DNS DoH解析服务器
  - tag: "BACKUP_DOH"
    type: "forward"
    args:
      concurrent: 1
      upstreams:
        - tag: apadpro_doh
          addr: "https://doh.apad.pro/dns-query"
          idle_timeout: 30
          enable_pipeline: false
          enable_http3: false
          insecure_skip_verify: false

    # 大陆DNS DoH解析服务器
  - tag: "CHINA_DOH"
    type: "forward"
    args:
      concurrent: 2
      upstreams:
        - tag: aliyun_doh
          addr: "https://223.5.5.5/dns-query"
          idle_timeout: 30
          enable_pipeline: true
          enable_http3: false
          insecure_skip_verify: false
        - tag: tencent_doh
          addr: "https://1.12.12.12/dns-query"
          idle_timeout: 30
          enable_pipeline: true
          enable_http3: false
          insecure_skip_verify: false

  # 翻墙节点、代理服务器节点域名数据集
  # 使用时，用 qname $CHINA_DOMAIN_SET 来匹配
  - tag: "PROXY_SERVER_DOMAIN_SET"
    type: "domain_set"
    args:
      files:  # 从文件载入
        - "./proxy_server_force_local_dns_domain.txt"

  # 大陆域名数据集
  # 使用时，用 qname $CHINA_DOMAIN_SET 来匹配
  - tag: "CHINA_DOMAIN_SET"
    type: "domain_set"
    args:
      exps:
        - "full:cn"
      files:  # 从文件载入
        - "./china_domain_list.txt"
        - "./my_direct_domain.txt"

  # 大陆IP数据集
  # 如果一个域名，并没有在大陆域名中命中，他会在海外DNS解析，解析可能返回大陆IP
  # 这个时候，需要用大陆DNS重新解析一遍，以更好命中CDN加速
  # 使用时，用 resp_ip  $CHINA_IP_SET 来匹配
  - tag: "CHINA_IP_SET"
    type: "ip_set"
    args:
      files:  # 从文件载入
        - "./china_ip_list.txt"
  
  
  # 缓存层逻辑链
  - tag: CC
    type: "sequence"
    args:
    #   - exec: query_summary "缓存" # 打印请求摘要
      - exec: $CACHE
      - matches: has_resp
        exec: accept
  
  # 大陆DNS解析逻辑链（会使用ECS_CHINA来加快国内域名速度）
  - tag: LO
    type: "sequence"
    args:
      - exec: query_summary "大陆"
      - exec: $ECS_CHINA # 附带ECS
      - exec: $CHINA_DOH
      - matches: "!resp_ip $CHINA_IP_SET" # 如果大陆DNS返回了不是国内的IP，则用海外解析一遍
        exec: mark 1 # 打标记
      - matches: mark 1 # 匹配标记
        exec: query_summary "海外重解"
      - matches: mark 1
        exec: $REMOTE_DOH
      - exec: accept
  
  # 强制使用大陆DNS解析并修改TTL 的逻辑链
  - tag: FL
    type: "sequence"
    args:
      - exec: query_summary "大陆（TTL）"
      - exec: $CHINA_DOH
      - exec: ttl 3600  # 修改TTL，秒
      - exec: accept
  
  # 远程DNS解析逻辑链
  - tag: RE
    type: "sequence"
    args:
      - exec: query_summary "海外"
      - exec: $REMOTE_DOH
      #如果海外远程DNS无响应，那么使用备用的DNS
      - matches: "!has_resp"  
        exec: mark 1
      - matches: mark 1
        exec: query_summary "备用兜底解析"
      - matches: mark 1
        exec: $BACKUP_DOH
      # 如果海外DNS 或 备用DNS返回了国内IP，则用国内解析一遍（为了防止解析出的IP舍近求远）
      - matches: resp_ip $CHINA_IP_SET 
        exec: mark 2
      - matches: mark 2
        exec: query_summary "大陆重解"
      - matches: mark 2
        exec: $CHINA_DOH
      - exec: accept

  # 主逻辑入口      
  - tag: "main"
    type: "sequence"
    args:
      # - exec: debug_print  # 打印细节
      # - exec: query_summary SUMM # 打印请求摘要
      # 处理PTR
      - exec: $REVERSE_LOOKUP
      # IPv4 结果优先（不返回IPv6结果）
      - exec: prefer_ipv4
      # 缓存层（经过CC逻辑链下面的逻辑，都会缓存在CC上，如果在CC中命中，就不会执行后面的逻辑链）
      - exec: jump CC
      # 翻墙节点、代理服务器的域名，强制使用大陆解析并修改ttl
      - matches: qname $PROXY_SERVER_DOMAIN_SET # 翻墙节点、代理服务器的域名
        exec: jump FL # 大陆（TTL）解析
      # 大陆域名
      - matches: qname $CHINA_DOMAIN_SET # 国内域名、直连域名
        exec: jump LO # 大陆DNS进行解析
      # 非大陆域名
      - exec: jump RE # 海外解析
      # 最终返回
      - exec: accept

# 启动 udp 和 tcp 服务器。
  - type: udp_server
    args:
      entry: main
      listen: ":55533"
  - type: tcp_server
    args:
      entry: main
      listen: ":55533"